// eslint-disable-next-line import/prefer-default-export
export const Test = [
  {
    id: '1',
    title: 'Review the calculations',
    grade: '1',
    test: 'Choose the smallest number',
    a_1: '87',
    a_2: '69',
    a_3: '56',
    a_4: '12',
    key: '4',
  },
  {
    id: '2',
    title: 'Review the calculations',
    grade: '1',
    test: 'Choose the largest number',
    a_1: '87',
    a_2: '69',
    a_3: '56',
    a_4: '12',
    key: '1',
  },
  {
    id: '3',
    title: 'Review the calculations',
    grade: '1',
    test: 'The next number for 23 is',
    a_1: '87',
    a_2: '24',
    a_3: '56',
    a_4: '12',
    key: '2',
  },
  {
    id: '4',
    title: 'Review the calculations',
    grade: '1',
    test: 'The next number for 24 is',
    a_1: '87',
    a_2: '24',
    a_3: '25',
    a_4: '12',
    key: '3',
  },{
    id: '5',
    title: 'Review the calculations',
    grade: '1',
    test: 'The next number for 67 is',
    a_1: '87',
    a_2: '24',
    a_3: '25',
    a_4: '68',
    key: '4',
  },

];

